[build]
  # This tells Netlify to publish the root directory.
  publish = "."

[[headers]]
  for = "/*.glb"
  [headers.values]
    Content-Type = "model/gltf-binary"

[[headers]]
  for = "/**/*.glb"
  [headers.values]
    Content-Type = "model/gltf-binary"

[[headers]]
  for = "/*.usdz"
  [headers.values]
    Content-Type = "model/vnd.usdz+zip"

[[headers]]
  for = "/**/*.usdz"
  [headers.values]
    Content-Type = "model/vnd.usdz+zip"

